# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Create GitHub Release?'
        required: true
        type: boolean
        default: false

permissions:
  contents: write

env:
  APP_VERSION: "1.0.0" 

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build EXE with PyInstaller
        run: python -m PyInstaller AirMonitor.spec

      - name: Package EXE and HTML into ZIP
        shell: pwsh
        run: |
          $fullVersion = "${{ env.APP_VERSION }}-${{ github.run_number }}"
          New-Item -ItemType Directory -Path "bundle" -Force
          $exe = Get-ChildItem "dist/*.exe" | Select-Object -First 1
          $newExeName = "$($exe.BaseName)_$fullVersion$($exe.Extension)"
          Move-Item -Path $exe.FullName -Destination "bundle/$newExeName"
          Copy-Item -Path "srv_app/index.html" -Destination "bundle/index.html"
          $zipName = "AirMonitor_$fullVersion.zip"
          Compress-Archive -Path "bundle/*" -DestinationPath $zipName
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: airmon-app
          path: AirMonitor_*.zip

      - name: Release Manual Build
        uses: softprops/action-gh-release@v2
        if: github.event.inputs.make_release == 'true'
        with:
          files: AirMonitor_*.zip
          tag_name: "v${{ env.APP_VERSION }}-${{ github.run_number }}"
          name: "Release v${{ env.APP_VERSION }}-${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
